# NumPy 101

To properly use OpenCV (and actually understand what's going on) it's important to understand what NumPy is and the purpose it exists to serve. You *can* work with OpenCV without knowing it, but some things are going to get confusing, and eventually things just won't make sense.

## What is it?
NumPy is, at its most simple, a better version of a handful of native python features and libraries. It offers much better math with a much wider range of options, but more importantly it improves upon python's lists/arrays. If you've ever done any sort of matrix math, you know how useful matrices can be (solving systems of linear equations, for example) -- numpy is here to give us those tools. Vectors, matrices, dot products, matrix multiplication, inverse matrices, you name it, they probably have it.

But how does it relate to computer vision? Well, images are just collections of numbers. You may be familiar with RGB pixels (and if you're not, you'll get there), where any given pixel on a screen has 3 individual LEDs which are red, green, and blue. The way in which these 3 basic colors mix give us the wide range of colors we see on our screens, and they do that by adjusting the brightness of each of these 3 smaller color pixels. Say red and green both have a brightness of 0 and blue has a brightness of 100%, what color do you think you'll see? How about if red has 50% and blue has 50%? (The answers are blue and purple respectively)

To the computer, these brightness values are stored as integers ranging from (and including) 0 to 255 (why do you think 255 is the max value?). Then, it's useful to have some way to represent each one of these pixels with their 3 colors -- and in comes NumPy. NumPy allows us to not only have an array of these 3 integer color values, it also allows us to store them in another array, representing the whole image! Take the following example, a 1 pixel by 3 pixel image of a red pixel, green pixel, and blue pixel respectively:

```
[
    [[255, 0, 0], [0, 255, 0], [0, 0, 255]]
]
```

Now lets get our feet wet with some code. We'll start by importing numpy and renaming it to "np". This is a convention you'll see everywhere, it just exists to shorten the amount of typing.

In [2]:
import numpy as np

Now we'll create our first NumPy array.

In [3]:
my_array = np.array([1,2,3])
print(my_array)

[1 2 3]


Easy! Now lets create another one and do some math with them.

In [4]:
my_second_array = np.array([4,5,6])

print(my_array + my_second_array)
print(my_second_array - my_array)
print(my_array.dot(my_second_array))

[5 7 9]
[3 3 3]
32


Hopefully it's already becoming clear how useful NumPy is. A quick note about those operations, if any didn't make sense to you (like the ``.dot`` for example) don't worry, that will be covered later on -- right now we're just trying to get up to speed before doing OpenCV.

Now lets try and make a NumPy array exactly like that 1x3 image from earlier. A quick note about notation, array dimensions are usually referred to as rows x columns, i.e. 1 row x 3 columns. 

In [5]:
my_small_image = np.array([
    [255, 0, 0], [0, 255, 0], [0, 0, 255]
])
print(my_small_image)

[[255   0   0]
 [  0 255   0]
 [  0   0 255]]


We won't now, but with one small change we could render that as an image if we wanted to. 

What is that small change? Well, recall from the intro that NumPy offers improvements on standard python features -- that isn't limited to the existence of arrays! We made an array of integers, but what if I wanted to make an array of floats? What if I want 32 bit floats? What about an unsigned integer? That's what NumPy gives us, and that's the small change -- OpenCV expects an array of unsigned 8-bit integers (call back to 255 being the max color value...), and we can change the array to meet that. (If you're confused on these types, here's a short article https://www.thoughtco.com/definition-of-unsigned-958174)

In [6]:
my_uint8_image = my_small_image.astype(np.uint8)
print(my_uint8_image)

# Alternatively, the type can be passed directly in to np.array upon declaration:
my_small_image_2 = np.array([
    [255, 0, 0],
    [0, 255, 0],
    [0, 0, 255]
], dtype=np.uint8)

[[255   0   0]
 [  0 255   0]
 [  0   0 255]]


Sometimes it's useful to create an array of zeros, or maybe all ones. Sometimes maybe you'll want an array of random numbers, or maybe you'll want an identity matrix (will be covered in the math). NumPy gives us the ability to easily create any of these. All we need to know is the rows and columns (in that order).

Note - the array's we've made so far have been either 1 or 2 dimensional. We aren't limited to just those two, and all of these methods are n-dimensional, i.e. we can make any dimension $n$

In [7]:

all_zeroes = np.zeros([3,3], dtype=np.uint8)
all_ones = np.ones([3,3], dtype=np.uint8)
all_random = np.random.randint(10, size=(3,3))
identity = np.eye(3)

print(all_zeroes)
print(all_ones)
print(all_random)
print(identity)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[3 3 9]
 [6 9 7]
 [7 5 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


At this point what needs to be covered for OpenCV has been, so feel free to move on to that part if you want. It is *highly* recommended to read through and understand the math, but not required. As for more NumPy, the online documentation is high quality so Google is your friend.

## Math.

We'll start by just naming a few things. 

First, a scalar. A scalar is just a number. That's it. It's just a number that has no other information with it other than it and its sign. 

Second, a vector is simply a collection of numbers which, in our case, are one dimensional. A vector can represent a million different things -- if you have a physics background, it's a force with direction and magnitude. If you have more of a math background, you may know it as simply a coordinate pair/triple. The cool thing about vectors (and linear algebra, the field they come from) is that they can represent any of those things! We use vectors in a couple of different ways, like representing the individual pixels in an image, or maybe a point in 3D space around the car, or maybe even the acceleration of the car. There's a couple of different notations for a vector, but most commonly you'll see $$\vec{x}=<u, v>$$ or $$\vec{x}=\begin{bmatrix} u \\ v \end{bmatrix}$$. The former notation is used a lot in vector calculus, the latter is common to see in linear algebra.

Third and final, matrices. A matrix is just a collection of vectors (see a pattern?). These are just noted as $$\begin{bmatrix}
r_1c_1 & r_1c_2 & r_1c_3 \\
r_2c_1 & r_2c_2 & r_3c_3 \\
r_3c_1 & r_3c_2 & r_3c_3 \\ \end{bmatrix}$$ and their dimension is usually described as their rows x columns -- just like NumPy arrays.

1D NumPy arrays are just vectors, and n-dimensional NumPy arrays are just matrices.

### Vector-Scalar multiplication

Multiplying a vector and scalar is super simple -- if you have the scalar $a$ and the vector $<u,v>$ then $a<u,v>=<au,av>$. The scalar just multiplies into each entry.

### Dot Product

The dot product is a vector operation which gives you a scalar. That scalar can essentially describe "how much" of the vectors are point in each other's direction.

Assuming $\vec{u} = <u_1, u_2, u_3>$ and $\vec{v}=<v_1,v_2,v_3>$, the dot product of $\vec{u}$ and $\vec{v}$ is shown as
$$
\vec{u} \ \ \cdot \ \ \vec{v} \ = u_1v_1 \ + \ u_2v_2 \ + \ u_3v_3
$$
or
$$
\vec{u} \ \ \cdot \ \ \vec{v} \ = |\vec{u}| |\vec{v}| \cos(\theta)
$$
where $\theta$ is the angle formed between $\vec{u}$ and $\vec{v}$

If the dot product is...
- Positive: the angle between $\vec{u}$ and $\vec{v}$ is less than 90 degrees (acute)
- Negative: the angle between $\vec{u}$ and $\vec{v}$ is greater than 90 degrees (obtuse)
- Zero: $\vec{u}$ and $\vec{v}$ are parallel

### Vector-Matrix multiplication
Matrix-Matrix multiplication is messy and best left to places that have already covered it (https://www.mathsisfun.com/algebra/matrix-multiplying.html). Thankfully, vector-matrix multiplication is much simpler and is used all the time.

The easiest way to explain it is to show it:
$$
\begin{bmatrix} x \\ y \\ z \\ \end{bmatrix}
\begin{bmatrix} a_1 & a_2 & a_3 \\ b_1 & b_2 & b_3 \\ c_1 & c_2 & c_3 \\ \end{bmatrix} =
\begin{bmatrix} xa_1 + ya_2 + za_3 \\ xb_1 + yb_2 + zb_3 \\ xc_1 + yc_2 + zd_3 \\ \end{bmatrix}
$$

Essentially, the matrix splits into vectors by columns, and the entries in the multiplied vector become scalars to multiply each matrix vector.

### Identity matrix

When it comes to matrix algebra, the identity matrix is essentially the new "1". Any vector multiplied into the correspondng identity matrix is just that vector, any matrix times an identity matrix is just the matrix, the list goes on. What they actually are and what they actually represent is shockingly complex and if you're interested, take linear algebra -- but for us, what I've listed is all you'll ever need to know.

The identity matrix itself is just a square matrix (num rows = num cols) with 1s along the main diagonal and 0s everywhere else. These don't have a specific size and can be any size $n$, it just needs to be squared. Often, you'll see them noted as $I_n$.

$$I_3 = \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \\ \end{bmatrix}$$

That's all we'll go through, so here are some examples of this stuff in action with NumPy.

In [8]:
a = np.array([1, 2, 3])
b = np.array([0,0,0])
c = np.array([1,1,1])
i = np.eye(3)

m = np.array([
    [1,2,3],
    [3,2,1],
    [1,2,3]
])

print(a.dot(c))
print(b.dot(a))
print(a.dot(i))
print(a.dot(m)) # in NumPY vector-matrix multiplication is the dot product of the vector and matrix
print(b.dot(m))

6
0
[1. 2. 3.]
[10 12 14]
[0 0 0]
